### ISSUE TITLE
Demo Broken in Chrome?

### ISSUE THREAD

**Issue by crh3675** [onaci/leaflet-velocity#88]
Demo not working in Chrome 
![image](https://user-images.githubusercontent.com/309006/173205911-f0231d1d-6be1-45ca-84e5-e3b9cc52d908.png)

**Comment by brentfraser** [comment]
The live demo works for me on 
  Version 102.0.5005.115 (Official Build) snap (64-bit)
(Ubuntu 20.04.4 LTS)

Note you need to enable one of the dynamic layers using the layer control.

**Comment by danwild** [comment]
Closing, as "not working" is far too vague.

Please provide more information about what exactly is not working, what you have tried, any errors in console etc.
